
keycloak:
  realm: REALM_NAME
  server-url: KEYCLOAK_SERVER
  client-id: CLIENT_ID
  client-secret: CLIENT_SECRET

app:
  default-role: DEFAULT_ROLE

spring:
  application:
    name: stackquiz-api

  threads:
    virtual:
      enabled: true

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB

  datasource:
    url: DB_URL
    username: DB_USER
    password: DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: HOST_NAME
      port: PORT_NUMBER
      database: 0
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ISSUER_URL
server:
  port: 9999